name: Lint Pull Request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: write

jobs:
  main:
    name: Validate Pull Request title
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR title
        uses: amannn/action-semantic-pull-request@v5.5.3
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment when title is invalid
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        uses: marocchino/sticky-pull-request-comment@v2.9.4
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋🏼

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            Details:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```
      - name: Remove validation comment when fixed
        if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2.9.4
        with:
          header: pr-title-lint-error
          delete: true
